# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
early_access: true

reviews:
  changed_files_summary: false
  sequence_diagrams: false
  estimate_code_review_effort: false
  related_issues: false
  related_prs: false
  suggested_labels: false
  finishing_touches:
    unit_tests:
      enabled: false
