 
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/account/components/SettingsWidget': RouteRecordInfo<'/account/components/SettingsWidget', '/account/components/SettingsWidget', Record<never, never>, Record<never, never>>,
    '/account/SettingsView': RouteRecordInfo<'/account/SettingsView', '/account/SettingsView', Record<never, never>, Record<never, never>>,
    '/admin/AdminUserRolesView': RouteRecordInfo<'/admin/AdminUserRolesView', '/admin/AdminUserRolesView', Record<never, never>, Record<never, never>>,
    '/admin/AnnouncementsView': RouteRecordInfo<'/admin/AnnouncementsView', '/admin/AnnouncementsView', Record<never, never>, Record<never, never>>,
    '/admin/components/dialogs/DeleteUserDialog': RouteRecordInfo<'/admin/components/dialogs/DeleteUserDialog', '/admin/components/dialogs/DeleteUserDialog', Record<never, never>, Record<never, never>>,
    '/admin/components/dialogs/EditUserDialog': RouteRecordInfo<'/admin/components/dialogs/EditUserDialog', '/admin/components/dialogs/EditUserDialog', Record<never, never>, Record<never, never>>,
    '/admin/components/dialogs/UserDetailsDialog': RouteRecordInfo<'/admin/components/dialogs/UserDetailsDialog', '/admin/components/dialogs/UserDetailsDialog', Record<never, never>, Record<never, never>>,
    '/admin/components/UserManagementTable': RouteRecordInfo<'/admin/components/UserManagementTable', '/admin/components/UserManagementTable', Record<never, never>, Record<never, never>>,
    '/admin/dialogs/AdminUserRolesDialog': RouteRecordInfo<'/admin/dialogs/AdminUserRolesDialog', '/admin/dialogs/AdminUserRolesDialog', Record<never, never>, Record<never, never>>,
    '/admin/dialogs/AnnouncementCreateEditDialog': RouteRecordInfo<'/admin/dialogs/AnnouncementCreateEditDialog', '/admin/dialogs/AnnouncementCreateEditDialog', Record<never, never>, Record<never, never>>,
    '/admin/dialogs/AnnouncementDeleteConfirmationDialog': RouteRecordInfo<'/admin/dialogs/AnnouncementDeleteConfirmationDialog', '/admin/dialogs/AnnouncementDeleteConfirmationDialog', Record<never, never>, Record<never, never>>,
    '/admin/dialogs/AnnouncementDetailDialog': RouteRecordInfo<'/admin/dialogs/AnnouncementDetailDialog', '/admin/dialogs/AnnouncementDetailDialog', Record<never, never>, Record<never, never>>,
    '/admin/UserManagementView': RouteRecordInfo<'/admin/UserManagementView', '/admin/UserManagementView', Record<never, never>, Record<never, never>>,
    '/Auth': RouteRecordInfo<'/Auth', '/Auth', Record<never, never>, Record<never, never>>,
    '/executive/components/ActionRequired': RouteRecordInfo<'/executive/components/ActionRequired', '/executive/components/ActionRequired', Record<never, never>, Record<never, never>>,
    '/executive/components/ExecutiveWidget': RouteRecordInfo<'/executive/components/ExecutiveWidget', '/executive/components/ExecutiveWidget', Record<never, never>, Record<never, never>>,
    '/executive/components/HeaderBar': RouteRecordInfo<'/executive/components/HeaderBar', '/executive/components/HeaderBar', Record<never, never>, Record<never, never>>,
    '/executive/components/KpiCards': RouteRecordInfo<'/executive/components/KpiCards', '/executive/components/KpiCards', Record<never, never>, Record<never, never>>,
    '/executive/components/MonthlyChart': RouteRecordInfo<'/executive/components/MonthlyChart', '/executive/components/MonthlyChart', Record<never, never>, Record<never, never>>,
    '/executive/components/QuickStatsCards': RouteRecordInfo<'/executive/components/QuickStatsCards', '/executive/components/QuickStatsCards', Record<never, never>, Record<never, never>>,
    '/executive/components/TopProducts': RouteRecordInfo<'/executive/components/TopProducts', '/executive/components/TopProducts', Record<never, never>, Record<never, never>>,
    '/executive/dialogs/SuppliersDialog': RouteRecordInfo<'/executive/dialogs/SuppliersDialog', '/executive/dialogs/SuppliersDialog', Record<never, never>, Record<never, never>>,
    '/executive/ExecutiveView': RouteRecordInfo<'/executive/ExecutiveView', '/executive/ExecutiveView', Record<never, never>, Record<never, never>>,
    '/finance/FinanceView': RouteRecordInfo<'/finance/FinanceView', '/finance/FinanceView', Record<never, never>, Record<never, never>>,
    '/ForbiddenView': RouteRecordInfo<'/ForbiddenView', '/ForbiddenView', Record<never, never>, Record<never, never>>,
    '/hometab/HomeAnnouncements': RouteRecordInfo<'/hometab/HomeAnnouncements', '/hometab/HomeAnnouncements', Record<never, never>, Record<never, never>>,
    '/hometab/HomeLogs': RouteRecordInfo<'/hometab/HomeLogs', '/hometab/HomeLogs', Record<never, never>, Record<never, never>>,
    '/HomeView': RouteRecordInfo<'/HomeView', '/HomeView', Record<never, never>, Record<never, never>>,
    '/logs/components/LogsWidget': RouteRecordInfo<'/logs/components/LogsWidget', '/logs/components/LogsWidget', Record<never, never>, Record<never, never>>,
    '/logs/LogsView': RouteRecordInfo<'/logs/LogsView', '/logs/LogsView', Record<never, never>, Record<never, never>>,
    '/NotFound': RouteRecordInfo<'/NotFound', '/NotFound', Record<never, never>, Record<never, never>>,
    '/otherTab/Page1View': RouteRecordInfo<'/otherTab/Page1View', '/otherTab/Page1View', Record<never, never>, Record<never, never>>,
    '/purchasing/components/IssuePOModal': RouteRecordInfo<'/purchasing/components/IssuePOModal', '/purchasing/components/IssuePOModal', Record<never, never>, Record<never, never>>,
    '/purchasing/components/PODetailModal': RouteRecordInfo<'/purchasing/components/PODetailModal', '/purchasing/components/PODetailModal', Record<never, never>, Record<never, never>>,
    '/purchasing/components/PRDetailModal': RouteRecordInfo<'/purchasing/components/PRDetailModal', '/purchasing/components/PRDetailModal', Record<never, never>, Record<never, never>>,
    '/purchasing/components/PurchaseOrderList': RouteRecordInfo<'/purchasing/components/PurchaseOrderList', '/purchasing/components/PurchaseOrderList', Record<never, never>, Record<never, never>>,
    '/purchasing/components/PurchaseRequisition': RouteRecordInfo<'/purchasing/components/PurchaseRequisition', '/purchasing/components/PurchaseRequisition', Record<never, never>, Record<never, never>>,
    '/purchasing/components/PurchaseRequisitionList': RouteRecordInfo<'/purchasing/components/PurchaseRequisitionList', '/purchasing/components/PurchaseRequisitionList', Record<never, never>, Record<never, never>>,
    '/purchasing/PurchaseOrdersView': RouteRecordInfo<'/purchasing/PurchaseOrdersView', '/purchasing/PurchaseOrdersView', Record<never, never>, Record<never, never>>,
    '/purchasing/PurchasingListView': RouteRecordInfo<'/purchasing/PurchasingListView', '/purchasing/PurchasingListView', Record<never, never>, Record<never, never>>,
    '/purchasing/PurchasingView': RouteRecordInfo<'/purchasing/PurchasingView', '/purchasing/PurchasingView', Record<never, never>, Record<never, never>>,
    '/sales/SalesView': RouteRecordInfo<'/sales/SalesView', '/sales/SalesView', Record<never, never>, Record<never, never>>,
    '/suppliers/components/SuppliersCRUD': RouteRecordInfo<'/suppliers/components/SuppliersCRUD', '/suppliers/components/SuppliersCRUD', Record<never, never>, Record<never, never>>,
    '/suppliers/SuppliersView': RouteRecordInfo<'/suppliers/SuppliersView', '/suppliers/SuppliersView', Record<never, never>, Record<never, never>>,
    '/warehouse/components/POlistWidget': RouteRecordInfo<'/warehouse/components/POlistWidget', '/warehouse/components/POlistWidget', Record<never, never>, Record<never, never>>,
    '/warehouse/dialogs/PODetailModal': RouteRecordInfo<'/warehouse/dialogs/PODetailModal', '/warehouse/dialogs/PODetailModal', Record<never, never>, Record<never, never>>,
    '/warehouse/dialogs/PODetailViewModal': RouteRecordInfo<'/warehouse/dialogs/PODetailViewModal', '/warehouse/dialogs/PODetailViewModal', Record<never, never>, Record<never, never>>,
    '/warehouse/ProductsListView': RouteRecordInfo<'/warehouse/ProductsListView', '/warehouse/ProductsListView', Record<never, never>, Record<never, never>>,
    '/warehouse/WareHouseView': RouteRecordInfo<'/warehouse/WareHouseView', '/warehouse/WareHouseView', Record<never, never>, Record<never, never>>,
  }
}
