 
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/account/components/SettingsWidget': RouteRecordInfo<'/account/components/SettingsWidget', '/account/components/SettingsWidget', Record<never, never>, Record<never, never>>,
    '/account/SettingsView': RouteRecordInfo<'/account/SettingsView', '/account/SettingsView', Record<never, never>, Record<never, never>>,
    '/admin/AdminUserRolesView': RouteRecordInfo<'/admin/AdminUserRolesView', '/admin/AdminUserRolesView', Record<never, never>, Record<never, never>>,
    '/admin/AnnouncementsView': RouteRecordInfo<'/admin/AnnouncementsView', '/admin/AnnouncementsView', Record<never, never>, Record<never, never>>,
    '/admin/components/dialogs/DeleteUserDialog': RouteRecordInfo<'/admin/components/dialogs/DeleteUserDialog', '/admin/components/dialogs/DeleteUserDialog', Record<never, never>, Record<never, never>>,
    '/admin/components/dialogs/EditUserDialog': RouteRecordInfo<'/admin/components/dialogs/EditUserDialog', '/admin/components/dialogs/EditUserDialog', Record<never, never>, Record<never, never>>,
    '/admin/components/dialogs/UserDetailsDialog': RouteRecordInfo<'/admin/components/dialogs/UserDetailsDialog', '/admin/components/dialogs/UserDetailsDialog', Record<never, never>, Record<never, never>>,
    '/admin/components/UserManagementTable': RouteRecordInfo<'/admin/components/UserManagementTable', '/admin/components/UserManagementTable', Record<never, never>, Record<never, never>>,
    '/admin/dialogs/AdminUserRolesDialog': RouteRecordInfo<'/admin/dialogs/AdminUserRolesDialog', '/admin/dialogs/AdminUserRolesDialog', Record<never, never>, Record<never, never>>,
    '/admin/dialogs/AnnouncementCreateEditDialog': RouteRecordInfo<'/admin/dialogs/AnnouncementCreateEditDialog', '/admin/dialogs/AnnouncementCreateEditDialog', Record<never, never>, Record<never, never>>,
    '/admin/dialogs/AnnouncementDeleteConfirmationDialog': RouteRecordInfo<'/admin/dialogs/AnnouncementDeleteConfirmationDialog', '/admin/dialogs/AnnouncementDeleteConfirmationDialog', Record<never, never>, Record<never, never>>,
    '/admin/dialogs/AnnouncementDetailDialog': RouteRecordInfo<'/admin/dialogs/AnnouncementDetailDialog', '/admin/dialogs/AnnouncementDetailDialog', Record<never, never>, Record<never, never>>,
    '/admin/UserManagementView': RouteRecordInfo<'/admin/UserManagementView', '/admin/UserManagementView', Record<never, never>, Record<never, never>>,
    '/Auth': RouteRecordInfo<'/Auth', '/Auth', Record<never, never>, Record<never, never>>,
    '/executive/ExecutiveView': RouteRecordInfo<'/executive/ExecutiveView', '/executive/ExecutiveView', Record<never, never>, Record<never, never>>,
    '/finance/FinanceView': RouteRecordInfo<'/finance/FinanceView', '/finance/FinanceView', Record<never, never>, Record<never, never>>,
    '/ForbiddenView': RouteRecordInfo<'/ForbiddenView', '/ForbiddenView', Record<never, never>, Record<never, never>>,
    '/hometab/HomeAnnouncements': RouteRecordInfo<'/hometab/HomeAnnouncements', '/hometab/HomeAnnouncements', Record<never, never>, Record<never, never>>,
    '/hometab/HomeLogs': RouteRecordInfo<'/hometab/HomeLogs', '/hometab/HomeLogs', Record<never, never>, Record<never, never>>,
    '/HomeView': RouteRecordInfo<'/HomeView', '/HomeView', Record<never, never>, Record<never, never>>,
    '/inhouse/components/CustomerCRUD': RouteRecordInfo<'/inhouse/components/CustomerCRUD', '/inhouse/components/CustomerCRUD', Record<never, never>, Record<never, never>>,
    '/inhouse/components/InhouseOrders': RouteRecordInfo<'/inhouse/components/InhouseOrders', '/inhouse/components/InhouseOrders', Record<never, never>, Record<never, never>>,
    '/inhouse/components/OrderDetailDialog': RouteRecordInfo<'/inhouse/components/OrderDetailDialog', '/inhouse/components/OrderDetailDialog', Record<never, never>, Record<never, never>>,
    '/inhouse/components/RaiseOrderDialog': RouteRecordInfo<'/inhouse/components/RaiseOrderDialog', '/inhouse/components/RaiseOrderDialog', Record<never, never>, Record<never, never>>,
    '/inhouse/CustomersView': RouteRecordInfo<'/inhouse/CustomersView', '/inhouse/CustomersView', Record<never, never>, Record<never, never>>,
    '/inhouse/InhouseOrdersView': RouteRecordInfo<'/inhouse/InhouseOrdersView', '/inhouse/InhouseOrdersView', Record<never, never>, Record<never, never>>,
    '/logs/LogsView': RouteRecordInfo<'/logs/LogsView', '/logs/LogsView', Record<never, never>, Record<never, never>>,
    '/NotFound': RouteRecordInfo<'/NotFound', '/NotFound', Record<never, never>, Record<never, never>>,
    '/otherTab/Page1View': RouteRecordInfo<'/otherTab/Page1View', '/otherTab/Page1View', Record<never, never>, Record<never, never>>,
    '/purchasing/components/IssuePOModal': RouteRecordInfo<'/purchasing/components/IssuePOModal', '/purchasing/components/IssuePOModal', Record<never, never>, Record<never, never>>,
    '/purchasing/components/PODetailModal': RouteRecordInfo<'/purchasing/components/PODetailModal', '/purchasing/components/PODetailModal', Record<never, never>, Record<never, never>>,
    '/purchasing/components/PRDetailModal': RouteRecordInfo<'/purchasing/components/PRDetailModal', '/purchasing/components/PRDetailModal', Record<never, never>, Record<never, never>>,
    '/purchasing/components/PurchaseOrderList': RouteRecordInfo<'/purchasing/components/PurchaseOrderList', '/purchasing/components/PurchaseOrderList', Record<never, never>, Record<never, never>>,
    '/purchasing/components/PurchaseRequisition': RouteRecordInfo<'/purchasing/components/PurchaseRequisition', '/purchasing/components/PurchaseRequisition', Record<never, never>, Record<never, never>>,
    '/purchasing/components/PurchaseRequisitionList': RouteRecordInfo<'/purchasing/components/PurchaseRequisitionList', '/purchasing/components/PurchaseRequisitionList', Record<never, never>, Record<never, never>>,
    '/purchasing/PurchaseOrdersView': RouteRecordInfo<'/purchasing/PurchaseOrdersView', '/purchasing/PurchaseOrdersView', Record<never, never>, Record<never, never>>,
    '/purchasing/PurchasingListView': RouteRecordInfo<'/purchasing/PurchasingListView', '/purchasing/PurchasingListView', Record<never, never>, Record<never, never>>,
    '/purchasing/PurchasingView': RouteRecordInfo<'/purchasing/PurchasingView', '/purchasing/PurchasingView', Record<never, never>, Record<never, never>>,
    '/sales/components/OutletInventory': RouteRecordInfo<'/sales/components/OutletInventory', '/sales/components/OutletInventory', Record<never, never>, Record<never, never>>,
    '/sales/components/PosPaymentDialog': RouteRecordInfo<'/sales/components/PosPaymentDialog', '/sales/components/PosPaymentDialog', Record<never, never>, Record<never, never>>,
    '/sales/components/PosReceiptDialog': RouteRecordInfo<'/sales/components/PosReceiptDialog', '/sales/components/PosReceiptDialog', Record<never, never>, Record<never, never>>,
    '/sales/components/PosTerminal': RouteRecordInfo<'/sales/components/PosTerminal', '/sales/components/PosTerminal', Record<never, never>, Record<never, never>>,
    '/sales/components/RemittanceCRUD': RouteRecordInfo<'/sales/components/RemittanceCRUD', '/sales/components/RemittanceCRUD', Record<never, never>, Record<never, never>>,
    '/sales/components/RemittanceSubmitDialog': RouteRecordInfo<'/sales/components/RemittanceSubmitDialog', '/sales/components/RemittanceSubmitDialog', Record<never, never>, Record<never, never>>,
    '/sales/components/SalesDashboard': RouteRecordInfo<'/sales/components/SalesDashboard', '/sales/components/SalesDashboard', Record<never, never>, Record<never, never>>,
    '/sales/components/SalesHistory': RouteRecordInfo<'/sales/components/SalesHistory', '/sales/components/SalesHistory', Record<never, never>, Record<never, never>>,
    '/sales/components/StockTransferCRUD': RouteRecordInfo<'/sales/components/StockTransferCRUD', '/sales/components/StockTransferCRUD', Record<never, never>, Record<never, never>>,
    '/sales/components/StockTransferDetailDialog': RouteRecordInfo<'/sales/components/StockTransferDetailDialog', '/sales/components/StockTransferDetailDialog', Record<never, never>, Record<never, never>>,
    '/sales/components/StockTransferRequestDialog': RouteRecordInfo<'/sales/components/StockTransferRequestDialog', '/sales/components/StockTransferRequestDialog', Record<never, never>, Record<never, never>>,
    '/sales/components/VoidSaleDialog': RouteRecordInfo<'/sales/components/VoidSaleDialog', '/sales/components/VoidSaleDialog', Record<never, never>, Record<never, never>>,
    '/sales/InventoryView': RouteRecordInfo<'/sales/InventoryView', '/sales/InventoryView', Record<never, never>, Record<never, never>>,
    '/sales/PosView': RouteRecordInfo<'/sales/PosView', '/sales/PosView', Record<never, never>, Record<never, never>>,
    '/sales/RemittanceView': RouteRecordInfo<'/sales/RemittanceView', '/sales/RemittanceView', Record<never, never>, Record<never, never>>,
    '/sales/SalesHistoryView': RouteRecordInfo<'/sales/SalesHistoryView', '/sales/SalesHistoryView', Record<never, never>, Record<never, never>>,
    '/sales/SalesView': RouteRecordInfo<'/sales/SalesView', '/sales/SalesView', Record<never, never>, Record<never, never>>,
    '/sales/StockTransfersView': RouteRecordInfo<'/sales/StockTransfersView', '/sales/StockTransfersView', Record<never, never>, Record<never, never>>,
    '/suppliers/components/SuppliersCRUD': RouteRecordInfo<'/suppliers/components/SuppliersCRUD', '/suppliers/components/SuppliersCRUD', Record<never, never>, Record<never, never>>,
    '/suppliers/SuppliersView': RouteRecordInfo<'/suppliers/SuppliersView', '/suppliers/SuppliersView', Record<never, never>, Record<never, never>>,
    '/warehouse/components/POlistWidget': RouteRecordInfo<'/warehouse/components/POlistWidget', '/warehouse/components/POlistWidget', Record<never, never>, Record<never, never>>,
    '/warehouse/dialogs/PODetailModal': RouteRecordInfo<'/warehouse/dialogs/PODetailModal', '/warehouse/dialogs/PODetailModal', Record<never, never>, Record<never, never>>,
    '/warehouse/dialogs/PODetailViewModal': RouteRecordInfo<'/warehouse/dialogs/PODetailViewModal', '/warehouse/dialogs/PODetailViewModal', Record<never, never>, Record<never, never>>,
    '/warehouse/ProductsListView': RouteRecordInfo<'/warehouse/ProductsListView', '/warehouse/ProductsListView', Record<never, never>, Record<never, never>>,
    '/warehouse/StockTransfersReviewView': RouteRecordInfo<'/warehouse/StockTransfersReviewView', '/warehouse/StockTransfersReviewView', Record<never, never>, Record<never, never>>,
    '/warehouse/WareHouseView': RouteRecordInfo<'/warehouse/WareHouseView', '/warehouse/WareHouseView', Record<never, never>, Record<never, never>>,
  }
}
